[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://hershield-backend.railway.app/api/v1"

[[redirects]]
  from = "/api/*"
  to = "https://hershield-backend.railway.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { VITE_API_BASE_URL = "https://hershield-backend.railway.app/api/v1" }

[context.deploy-preview]
  environment = { VITE_API_BASE_URL = "https://hershield-backend.railway.app/api/v1" }

[context.branch-deploy]
  environment = { VITE_API_BASE_URL = "https://hershield-backend.railway.app/api/v1" }
